server:
  port: 8080
  servlet:
    context-path: /account

spring:
  datasource:
    url: jdbc:mysql://192.168.56.99:3306/ssm?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: root

  jpa:
    show-sql: true

